name: iris-feature-and-prediction-pipelines

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.9'

      - name: Install Jupyter
        run: |
          python -m pip install jupyter

      - name: Install scikit-learn
        run: python -m pip install scikit-learn==1.2.1

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Give execute permissions to bash script
        run: chmod +x ./src/01-module/scripts/run-feature-and-prediction-pipelines.sh

      - name: Pull latest changes from remote and rebase
        run: git pull origin main --rebase

      - name: Add files to commit
        run: git add assets/latest_iris.png assets/actual_iris.png assets/confusion_matrix.png assets/df_recent.png

      - name: Check for changes before commit
        run: |
          git diff --exit-code || git commit -m "Automated graph published"

      - name: Publish GitHub pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated graph published"
          branch: main
          file_pattern: assets/latest_iris.png assets/actual_iris.png assets/confusion_matrix.png assets/df_recent.png
          commit_options: '--no-verify --signoff'
          skip_dirty_check: true
          skip_fetch: false
          skip_checkout: false
          disable_globbing: true
          create_branch: false
