name: iris-feature-and-prediction-pipelines

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.9'

      - name: Install Jupyter
        run: |
          python -m pip install jupyter

      - name: Install scikit-learn
        run: python -m pip install scikit-learn==1.2.1

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Give execute permissions to bash script
        run: chmod +x ./src/01-module/scripts/run-feature-and-prediction-pipelines.sh

      - name: Fetch latest changes from remote and rebase
        run: |
          git fetch origin
          git rebase origin/main || echo "Rebase failed, please resolve conflicts manually"

      - name: Add files to commit
        run: git add assets/latest_iris.png assets/actual_iris.png assets/confusion_matrix.png assets/df_recent.png

      - name: Check if there are changes to commit
        run: |
          git diff --exit-code || echo "Changes detected, proceeding with commit"

      - name: Commit changes if detected
        run: |
          if ! git diff --exit-code; then
            git commit -m "Automated graph published" --no-verify --signoff
          else
            echo "No changes detected, skipping commit"
          fi

      - name: Force push changes (if needed)
        run: |
          git push origin main --force || echo "No changes to push"

      - name: Publish github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated graph published"
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: assets/latest_iris.png assets/actual_iris.png assets/confusion_matrix.png assets/df_recent.png
          repository: .
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          skip_dirty_check: true
          skip_fetch: false
          skip_checkout: false
          disable_globbing: true
          create_branch: false
